# Generated by Django 5.0.3 on 2024-06-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Transaction_type',
            new_name='transaction_type',
        ),
    ]
