# Generated by Django 5.0.3 on 2024-06-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_transaction_type_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='load_aproved',
            new_name='loan_aproved',
        ),
    ]
